; Update the ansible_host IPs below to match your actual Azure VM IPs
; (from `az vm list-ip-addresses --resource-group RG --output table`)

[frontend]
public-vm ansible_host=20.101.48.21 ansible_user=azureuser

[backend]
private-vm-1 ansible_host=10.0.0.132 ansible_user=azureuser
private-vm-2 ansible_host=10.0.0.133 ansible_user=azureuser

[ansible_master]
; this is typically localhost if you run ansible-playbook FROM the master VM,
; or its own entry if you're targeting it for provisioning from your local machine
ansible-master ansible_host=10.0.0.5 ansible_user=azureuser

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3